turi-code/SFrame

oss_src/fileio/fs_utils.cpp

HAS_HADOOP macro should be checked before trying to use hdfs API

Check whether HADOOP API is available

---

oss_src/sframe/odbc_connector.cpp

Before writing a table to a SQL database, we must find the max length
for each column to know how much memory to allocate for a row. Our code
to do this for string and image type columns was slightly wrong, as it
stopped calculating the maximum if it ever found a NULL in the column.
So whatever was the maximum so far in that segment was taken to be the
maximum. This caused an infrequent error in certain datasets. Fixed
with this.
Also made an error message a little more clear.

Bugfix: ODBC maximum string length calculation

---

oss_src/unity/python/sframe/_gl_pickle.py

The definition in https://github.com/dato-code/SFrame/blob/master/oss_src/unity/python/sframe/util/file_util.py does not have a kwarg named `silent`.

Remove unrecognized kwarg from s3_recursive_delete

---

oss_local_scripts/pip_requirements.txt
oss_src/fileio/dmlcio/s3_filesys.cc
oss_src/fileio/fileio_constants.cpp
oss_src/fileio/fileio_constants.hpp
oss_src/fileio/oss_webstor/wsconn.cpp
oss_src/fileio/s3_api.cpp
oss_src/unity/python/setup.py
oss_src/unity/python/sframe/sys_util.py

Fixes several SSL Certificate issues.
- Made all CURL calls use Python's Certifi store. This allows us to unify: i.e. if awscli works, we should work too. 
- Switch the DMLCIO S3 block reader to use https
- Added better error reporting from DMLCIO S3 block reader so we know when there is a certificate validation problem.
- Enable SSL certificate check in Windows

Ssl certificate issues

---

oss_src/cppipc/common/object_factory_impl.cpp
oss_src/lambda/worker_pool.hpp
oss_src/logger/log_rotate.cpp
oss_src/logger/logger.cpp
oss_src/process/CMakeLists.txt
oss_src/process/process.cpp
oss_src/process/process.hpp
oss_src/process/process_unix.cpp
oss_src/process/process_win.cpp
oss_src/unity/python/sframe/__init__.py
oss_src/unity/python/sframe/connect/main.py
oss_src/unity/python/sframe/connect/server.py
oss_src/unity/python/sframe/util/__init__.py
oss_src/unity/server/unity_server.cpp

When launching a process (unity_server or pylambda_worker in this
commit) make sure that if the process errors out, the error message is
delivered to the user in some form (either to terminal or log). Also
some commands in the top namespace to print the location of the log to
look for errors.
Testing was in the form of manual adversarial tests, as it involved
breaking a current installation by moving files around, or changing
other system stuff.

Improve logging when launching processes

---

configure

This is necessary because CMake for whatever
reason leaves the build scripts around even after cython files get
deleted. So we just delete the cython build directory during
configure and force those build scripts to be regenerated.

Cleans up cython directory on configure.

---

oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/test/test_sframe.py

Fixes the issue that
sf.append(sf2) may return exactly sf2 if sf is empty (or vice versa)
which leads to interesting issues where after:
a = sf.append(b)
Changes to a may affect b which is unexpected.

Fixes an append issue

---

oss_src/fileio/dmlcio/s3_filesys.cc
oss_src/unity/python/sframe/sys_util.py
oss_src/unity/python/sframe/test/test_file_util.py

Seems like letting CERT_DIR be the default value can cause problems on
some earlier versions on Linux. So we just force it to the empty string
which will allow us to *only* use the certificates in certifi

More certificate issues

---

oss_src/unity/extensions/internal_demo.cpp
oss_src/unity/python/sframe/cython/cy_variant.pyx
oss_src/unity/python/sframe/test/test_extensions.py

Conversion of SArray or SFrames to a C++ variant_type ends up
serializing the entire SFrame / SArray as a list.
```
>>> g=SFrame({'a':[1,2,3]})
>>> extensions._demo_identity({'b':g})
will return
{'b':[{'a':1},{'a':2},{'a':3}]} instead of {'b':SFrame...}
```

There was a regression in the python extension code

---

oss_src/sframe/CMakeLists.txt

A new version (spark_unity_0.4.jar) is uploaded to s3 bucket. We needed to update version number and md5 code here as well.

Update spark unity jar

---

oss_src/unity/python/sframe/sys_util.py

Since we are launching the pylambda_worker as a DLL from python.exe, we can no
longer expect the supporting DLLs we package within the egg to be found by it.
This augments the path of unity_server on Windows only to add the graphlab path
within site-packages. This environment is inherited by children.

Fix failure to find supporting DLLs on Win32

---

oss_src/unity/python/sframe/test/test_extensions.py

int and long are not so consistent going through the variant conversion.
But that's all right. Python silently upgrades int and longs.

Fix test for windows

---

oss_src/unity/python/sframe/_gl_pickle.py
oss_src/unity/python/sframe/test/test_gl_pickler.py

We can now do the following
```
sf1 = SFrame(range(10))
relative_path = 'tmp/%s' % self.filename
pickler = gl_pickle.GLPickler(relative_path)
pickler.dump(sf1)
pickler.close()
sf2 = gl_pickle.GLUnpickler(relative_path).load()
```
Previously, the '~' wasn't being expanded out to the home directory and was being saved to the current directory.

GLPickle expandvars and expanduser paths are now supported.

---

oss_src/random/random.hpp

Rename multinomial_normalized -> overloaded version of multinumial.
This name is needed in GLC.

Sync up the names of the multinomial sampler.

---

oss_src/fileio/fixed_size_cache_manager.cpp
oss_src/fileio/fixed_size_cache_manager.hpp

This PR doesn't change any functionality, but it makes it easier to
track down memory leaks elsewhere in the code base with valgrind or
heapprof:
1. std::unique_ptr is used in static global so valgrind doesn't
complain of lost memory.
2. new is used instead of malloc so an std::bad_alloc is raised when
something fails.

Minor memory management tweaks

---

oss_src/globals/globals.cpp

Remove warning of setting SSL CERT environment variable on engine start

Remove "warning" of setting global runtime config

---

oss_local_scripts/make_egg.sh

The wheel script was failing on Mac-10.11. I updated the version string in the make_egg script.

Added Mac.10-11 into the platform string for wheels.

---

oss_src/unity/python/sframe/sys_util.py

Added a call to kernel32.SetDllDirectory on windows platforms to force
loading of correct DLLs by pylambda workers.
This is confirmed to work when old openssl libraries are installed in c:\system32 or c:\windows\system32.

Fix for pylambda load directory on windows

---

oss_src/unity/python/sframe/data_structures/sframe.py

SFrame.print_rows also takes a file handle that enables the user to
redirect output to something other than stdout, like a file or a string
stream. By documenting this parameter this feature becomes easier to
discover.

Add a missing parameter to the docstring of SFrame.print_rows

---

oss_src/unity/extensions/CMakeLists.txt
oss_src/unity/extensions/cumulative_aggregates.cpp
oss_src/unity/extensions/cumulative_aggregates.hpp
oss_src/unity/lib/CMakeLists.txt
oss_src/unity/lib/gl_sarray.cpp
oss_src/unity/lib/gl_sarray.hpp
oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/test/test_sarray.py
oss_src/unity/server/unity_server_init.cpp
oss_test/unity/gl_sarray.cxx

- Added a cumulative aggregate abstraction.
- Added cumulative sum (serial version).
For a cumulative aggregate
y <- x.cumulative_aggregate(f, w_0)
An abstraction to perform cumulative aggregates which is computed as
y[i+1], w[i+1] = func(x[i], w[i])
where w[i] is some arbitary state.
A user can implement cumulative_sum as follows.
```
auto cumsum_agg = []
(const flexible_type& v, flexible_type& y) -> flexible_type {
y += v;
return y
};
out_sa = in_sa.cumulative_aggregate(agg_fn, 0);
```

Added an abstraction for cumulative aggregates.

---

oss_src/sframe/group_aggregate_value.hpp
oss_src/sframe/groupby_aggregate_operators.hpp

The bug occurs during the combining of two aggregates of type variance, or
stdev when either one of them is empty. In other words, the following two
edge cases fail.
void combine(const group_aggregate_value& other) {
...
if (_other.count == 0) {
return;
} else if (count == 0) {
mean = _other.mean;
count = _other.count;
M2 = _other.M2;
}
...
For debugging, I added an << operator for all aggregates.

Fixed a bug in the cumulative variance and stdev code.

---

oss_src/cppipc/server/comm_server.cpp
oss_src/cppipc/server/comm_server.hpp
oss_src/lambda/pylambda_worker.cpp
oss_src/lambda/python_api.cpp
oss_src/logger/CMakeLists.txt
oss_src/logger/logger.cpp
oss_src/logger/logger.hpp
oss_src/unity/python/sframe/_pylambda_worker.py
oss_src/unity/python/sframe/sys_util.py

Added in lots of diagnostic information for finding pylambda worker
issues.
- Errors are printed to sys.stderr, so they appear in the console.
- If GRAPHLAB_LAMBDA_WORKER_DEBUG_MODE is set to 1 as an environment
variable, then all log messages are pushed to stderr and detailed
progress messages are printed to the console.
Other changes:
- The comm_server only prints out diagnostic information if the
environment variable GRAPHLAB_COMM_SERVER_DEBUG_MODE is set
(Otherwise, all lambda worker events and pings are dumped to the
console.)

Improvements to the lambda diagnostics

---

oss_local_scripts/make_egg.sh

This ought to stabilize the travis build (which runs in docker, and so we see much more CPUs than we are actually allocated and we end up using a lot of memory).

restrict the number of threads used when running tests when num_procs is set

---

oss_src/unity/python/sframe/connect/server.py
oss_src/unity/python/sframe/util/__init__.py
oss_src/unity/server/unity_server.cpp

Update2:  It's ok to merge since the embeded server PR is built on top of this.
Update: As we remove unity_server, some of the fixes here is no longer valid, and others will be folded the new PR.
The server may fail starting under when either of the following
(rare) conditions is true:
1. when two import happen close together
2. when a previous unity_server process crashed and left behind
ipc file with same pid, which cannot be deleted.
The root causes are both using either pid or timestamp alone
to name important files.
This fix resolve the potential file name conflict by using both
pid and timestamp as process identifier.

Fix for rare server startup issue

---

oss_src/unity/python/sframe/connect/main.py

* There should not be a reference to GraphLab Create (this is the SFrame engine).
* There should not be a reference to Dato support (instead, we should direct users to GitHub since this is an open source project).

Change engine start error message for SFrame.

---

oss_src/fileio/CMakeLists.txt
oss_src/fileio/curl_downloader.cpp
oss_src/fileio/dmlcio/s3_filesys.cc
oss_src/fileio/oss_webstor/wsconn.cpp
oss_src/fileio/set_curl_options.cpp
oss_src/fileio/set_curl_options.hpp

This improves robustness of everything which uses curl here.
If the download speed is < 1 byte per second for more than 60 seconds,
we force a timeout + abort.

Set curl timeout options

---

oss_src/unity/python/sframe/cython/cy_flexible_type.pyx
oss_src/unity/python/sframe/test/test_sarray.py

This adds support for numpy.datetime64 and pandas.Timestamp.
Conversion from numpy.datetime64 results in a datetime.datetime with timezone set explicitly to UTC, since numpy stores its info in UTC and does not keep track of timezones.
Conversion from pandas.Timestamp uses that type's own "to_datetime" method.

Add support for numpy and pandas datetime objects

---

oss_src/sframe/sarray.hpp
oss_src/sframe/sframe.cpp
oss_src/unity/lib/unity_sarray.cpp
oss_src/unity/lib/unity_sframe.cpp

For for a memory leak when creating empty SFrame (no rows or no columns) and empty sarrays (no rows).
In addition, as an optimization we maintain one empty SArray and one empty SFrame. But there is an annoying termination race issue between 
- clearing of the cache files
- deletion of the empty SArray/SFrame
A proper solution is non-trivial. At the moment the cleanest solution is simply to leak the empty SArray / empty SFrame.

Fix for a memory leak when creating empty sframe or sarray

---

oss_src/unity/extensions/CMakeLists.txt
oss_src/unity/extensions/random_sframe_generation.cpp
oss_src/unity/extensions/random_sframe_generation.hpp
oss_src/unity/python/sframe/test/test_sframe_generation.py
oss_src/unity/python/sframe/util/__init__.py
oss_src/unity/python/sframe/util/sframe_generation.py

This pull request adds in generation utilities to create random
SFrames of many different types for testing and benchmarking.  The
generation is done efficiently in C++.  The routines existed prior to
this in C++, but this pull request tweaks the API based on practical
use cases, plus exposes them to python.
The new functions are:
util.generate_random_sframe
util.generate_random_regression_sframe
util.generate_random_classification_sframe
To use, specify the number of rows and the codes for the columns.  The
codes are outlined in detail in the documentation for the above
functions, and are:
n:  numeric column, uniform 0-1 distribution.
N:  numeric column, uniform 0-1 distribution, 1% NaNs.
r:  numeric column, uniform -100 to 100 distribution.
R:  numeric column, uniform -10000 to 10000 …

Random SFrame generation for testing and benchmarking

---

oss_src/globals/CMakeLists.txt
oss_src/logger/log_rotate.cpp

Replace single static thread with shared pointers for log rotation
thread. This allows multiple "begin_log_rotation()" and
"stop_log_rotation()" to be called within a single session. In Python,
we can stop and re-launch the embedded server.
"globals" depends on "process" due to getenv_str

Improve log_rotate, "globals" depends on "process"

---

oss_src/lambda/pylambda.cpp

Fix a bug that the captured lambda function was leaked and not released properly.

fix a memory leak in lambda worker

---

oss_src/cppipc/client/comm_client.cpp
oss_src/unity/python/sframe/connect/server.py
oss_src/unity/python/sframe/cython/cy_ipc.pxd
oss_src/unity/python/sframe/cython/cy_ipc.pyx
oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/toolkits/_main.py
oss_src/unity/server/unity_server.cpp
oss_src/unity/server/unity_server.hpp
oss_src/unity/server/unity_server_capi.cpp

Fix two issues: 1. log progress wasn't showing at console and 2. server side operations cannot be interrupted.
The new log progress printing does not go through cppipc anymore.
The first change is to make the logger's progress callback directly print to stdout.
The second change is to expose CAPI which the python client can use to directly switch on/off the global logger's callback.
For the ctrl-c issue, the call to comm_client::init() wasn't using the correct flag for ops_interruptable.
This fixes it.
Also purge unused cython functions of cppipc layer

Fix log progress printing and ctrl-c

---

oss_src/flexible_type/string_escape.cpp
oss_src/flexible_type/string_escape.hpp
oss_src/sframe/csv_line_tokenizer.cpp
oss_src/sframe/csv_writer.cpp
oss_src/sframe/csv_writer.hpp
oss_src/sframe/parallel_csv_parser.cpp
oss_src/unity/lib/unity_sframe.cpp
oss_src/unity/python/sframe/data_structures/sframe.py
oss_test/sframe/sframe_csv_test.cxx

- Improved consistency of export_csv. Make it respect quoting options better, and support the complete disabling of the escape character. (#143)
- Allowed read_csv with glob expressions to skip empty files
- Fixed an interesting parsing error (#145)

CSV Writer And Parser Fixes

---

oss_src/fileio/libhdfs_shim.cpp
oss_src/unity/python/sframe/util/__init__.py

Use more robust libjvm.dylib for libhdfs on OS X
Inject `/usr/libexec/java_home`/jre/lib/server/libjvm.dylib to
be the first search location for libjvm. This is the most robust
way to get the latest system libjvm.
Also fix another bug in hdfs protocol validation
This should resolve issue #159

Fix read/write hdfs

---

oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/data_structures/sframe_builder.py
oss_src/unity/python/sframe/test/dbapi2_mock/__init__.py
oss_src/unity/python/sframe/test/test_sframe.py
oss_src/unity/python/sframe/util/__init__.py

This patch gets my scenario tests (which I have to commit AFTER this is merged I think) to pass on sqlite3, psycopg2, and MySQLdb.
Issues addressed:
- Sometimes to_sql rearranged the data in the columns. This not only was
wrong, but caused schema type errors in some instances.
- Account for psycopg2's need to rollback if any cursor anywhere
encounters an exception.
- Account for MySQLdb's iterator behavior not matching sqlite3 or
psycopg2, by not using an iterator at all in from_sql..instead
switching to fetchone() and fetchmany(), which are actually in the
mandatory DBAPI2 standard (the iterator is optional). As a result,
added the "cursor_arraysize" parameter to from_sql to read data in
chunks from the DB.
- Account for sqlite3's lack of strong types by not failing if the
required type …

Fix several bugs in the DBAPI2 support

---

oss_src/fileio/fixed_size_cache_manager.cpp

To aid error messages and OOM exceptions, some allocations in the
fileio module were changed to new [] and delete[].  However, this
block also uses a realloc, which can cause a memory leak on delete or
other issues.

Fix for realloc/new mismatch in fileio.

---

oss_src/fileio/libhdfs_shim.cpp

because /usr/libexec/java_home returns a string with a "\n" at the end. It is necessary to strip whitespace.

#160 is incomplete

---

oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/test/test_sframe.py

This changes the default behavior of to_sql. to_sql will now submit data
expecting the column names in the SFrame to match up exactly to the
column names of the table it is inserting into. If this option is set to
False, then the old behavior will take over, where the data values in
the SFrame are simply submitted in order to the table without care of
what columns are in the table.
This also adds metrics and a message about the beta status of this API.

Add "use_exact_column_names" option to to_sql.

---

oss_src/unity/python/sframe/connect/server.py
oss_src/unity/python/sframe/cython/cy_ipc.pxd
oss_src/unity/python/sframe/cython/cy_ipc.pyx
oss_src/unity/python/sframe/cython/python_printer_callback.py
oss_src/unity/server/unity_server.cpp
oss_src/unity/server/unity_server.hpp
oss_src/unity/server/unity_server_capi.cpp

Progress printing to ipython/jupyter notebook is broken. as in progress messages now completely don't make it to ipython/jupyter notebook. This is extraordinarily annoying. The issue is that with removal of unity_server, logprogress now goes straight to stdout. However, ipython/jupyter notebook does not capture stdout. 
One solution is to return to the old zeromq queueing + callback mechanism. But that is not desirable since we are trying to remove zeromq. The alternate solution implemented here is to use the callback mechanism to push a cython function pointer all the way to the progress printer.

Restored incremental printout in IPython notebook

---

oss_src/unity/python/sframe/cython/cy_flexible_type.pyx
oss_src/unity/python/sframe/cython/cy_variant.pyx
oss_src/unity/python/sframe/test/test_extensions.py

Updated the logic in cy_variant.pyx to ensure that flexible types are
converted correctly.  Before, some types that should have been treated
as flexible types were converted to variant types instead.  This PR
ensures that such types are indeed converted correctly.  Tests included.

Flex types always converted correctly in cy_variant

---

oss_src/unity/python/sframe/test/test_io.py

re.match on path names is way to liberal with paths, and fails with a compilation error on unicode paths, which can sometimes be returned (it seems) by os.tempfile on windows.  Use fnmatch instead to do linux glob style matching.

Fixed path issue in test_io.

---

oss_src/unity/python/sframe/util/metric_tracker.py
oss_src/unity/python/sframe/util/sys_info.py

This change makes the system-info parts of metrics tracking code
reusable from elsewhere, for logging and debugging purposes. This allows
the following to be queried at the API level from outside the metrics
tracking code:
* distinct id
* version
* is_gpu
* build number
* sys info

Small refactor of metrics tracking code

---

oss_src/fileio/union_fstream.cpp
oss_src/fileio/union_fstream.hpp

Fix the bug where the fileio cache layer allows read of a
evicted cache_block.
The cache eviction relies on the evicting thread being the only
holder of the cache_block. However, the union_fstream took an optimization
to directly grab the underlying input stream of a cache_stream,
thus giving up the cahce_block handle, allowing eviction to happen.
The fix is to remember the orignal cachestream which holds reference to
the cache_block. This prevents the block from being evicted.

Fix incorrect cache eviction

---

oss_src/unity/python/sframe/test/test_sframe.py

PR #172 fails on Python 3 because of None comparisons.
- In Python 2: None < 1
- In Python 3: None < 2 returns an error.
The test case was changed to compare list([1,None]) where the order is
interchangable to comparisons on set([1,None]).

Python 3 fix for PR: #172 from dato-code/added-groupby-aggregates

---

oss_src/sgraph/sgraph_triple_apply.cpp

class batch_triple_apply_visitor needs a virtual destructor,
otherwise, class lambda_triple_apply_visitor which inherits
from it will not be properly cleared, and leaks memory.

Fix memory leak of triple_apply

---

oss_src/sframe_query_engine/operators/operator_properties.cpp
oss_src/unity/python/sframe/test/test_sframe.py

The following code fails due to the inability to prove that a and a2 have the
same length when performing the logical filter. The code is supposed to
selectively materialize the filter so that length can be proven. However,
due to a bug in the prove_equal_length method, that was not done.
```
g=SArray(range(10000))
g2=SArray(range(10000))
a=g[g>10]
a2=g2[g>10]
a[a2>20] # Fail here
```

Critical Bug fix to logical filter

---

oss_src/unity/ReplicateSDKSourceTree.cmake

- The SFrame SDK example does not work because a file in process was
missing. This file is now added to the sdk-generation.

Modified the code to generate the SDK.

---

configure
oss_local_scripts/make_egg.sh
oss_local_scripts/python_env.sh
oss_local_scripts/run_python_test.sh
oss_src/flexible_type/flexible_type_base_types.hpp
oss_src/sframe_query_engine/operators/lambda_transform.hpp
oss_src/unity/python/sframe/cython/cy_server.pyx
oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/util/cloudpickle.py

- fix to cloudpickle backward compatibility and recursive closure
support. To maintain compatibility with the old cloudpickle, the
argument structure to fill_function and make_skel_func must be
maintained. Some modifications are added to amintain this.
- A regression was discovered where lambdas which returns lists cannot
be correctly converted to array type.
- adding a little comment to flexible_type to avoid some
misunderstandings
- Removed LD_LIBRARY_PATH setting in make_egg and python_env. That
causes more problems than it solves. Be a bit more strategic about when LD_LIBRARY_PATH is set.

Some regression fixing bug fixes

---

oss_src/unity/extensions/grouped_sframe.cpp

The bug was also present in Line 183 of the following file.
(https://github.com/dato-code/SFrame/pull/183/files)
The bug did not trigger test failures because this is not a feature
exposed to the Python side.

[GroupedSFrame] Fixed a bug in group-info.

---

oss_src/unity/python/setup.py

Versions prior to 2.6 fail on Debian 8 because of that OS's lack of
opensslv3 support.

Move requests to latest version

---

oss_local_scripts/pip_requirements.txt
oss_src/unity/python/conf/dev.py
oss_src/unity/python/conf/prod.py
oss_src/unity/python/conf/qa.py
oss_src/unity/python/conf/unit.py
oss_src/unity/python/setup.py
oss_src/unity/python/sframe/util/config.py
oss_src/unity/python/sframe/util/metric_tracker.py

This change removes Mixpanel tracking from SFrame (was only tracking engine-started events). Metrics tracking still goes to CloudFront (if GLC license is present). The bucketize logic was only being used by Mixpanel so that is removed as well.

Remove Mixpanel tracking from SFrame

---

oss_src/unity/server/unity_server.cpp

On engine start the logprogress handler was automatically set to
default std:cout handler. Disable that and only use the python
callback handler seems to fix the issue.

fix logprogress miss the very first print

---

oss_src/unity/extensions/additional_sframe_utilities.cpp

Added void* to support callback data.
The bug is due to range_iterator dereferences to sframe_row::row not
std::vector. sframe_row::row is a row wrapper over column store, hense does not have the contiguous memory,
expected by the callback function. The fix is to copy it into contiguous memory.

Extend and fix the callback interface

---

oss_src/sframe/CMakeLists.txt

Version 0.5 of spark_unity.jar file (sync with the latest commit master in https://github.com/dato-code/spark-sframe).
Major changes in jar file are: 
1) remove dependency to custom pickler.
2) better support for nested data structure (json format).
3) better support for dataframe of map type.
4) datetime conversion is now supported (no timezone).
5) remove dependency to boost::python.
6) fix issue of dataframe of int with null values.

new version of spark_unity.jar (version 0.5)

---

oss_src/unity/python/sframe/cython/cy_flexible_type.pyx
oss_src/unity/python/sframe/test/test_sarray.py

Types are decimal.Decimal and datetime.timedelta, both converted to
float. The timedelta type will represent the number of seconds in the
interval.
Also handles the case of the NaT (Not a Time) type in pandas and numpy.
Addresses https://github.com/dato-code/documents/issues/3717
and https://github.com/dato-code/documents/issues/3755

Add SFrame recognition for two types

---

oss_src/process/process_unix.cpp
oss_src/startup_teardown/startup_teardown.cpp

The sigchld handler for reaping child process relies on a global
std::set which does process id bookkeeping. The global variable
could be destroyed before the the signal handler is called, causing
undefined behavior on termination.

Fix ephemeral crash/hang on termination due to sigchild handler

---

oss_src/unity/python/sframe/data_structures/sframe.py

Rather than having sys.stdout get evaluated in the function definition,
use `None` as a default value and replace None with stdout in the
function body. Not sure this is the right solution...

Naive fix to #106

---

oss_src/lambda/lambda_master.cpp
oss_src/lambda/pylambda_worker.cpp

This PR causes the shared memory construction to look for an
environment variable, GRAPHLAB_DISABLE_LAMBDA_SHM, and disable the
shared memory mechanism if this is set to "1".

Allow for forced fallback to local TCP.

---

oss_src/unity/extensions/random_sframe_generation.cpp

This was failing with an AssertionError in run_toolkit_function or something. This seems to fix it.

Fix the 'w' option in generate_random_sframe

---

oss_src/util/cityhash_gl.hpp
oss_test/util/cityhash_gl.cxx

Provides a 64bit -> 64bit version of the murmurhash for use on hash tables that take an index, and want to get the index back.

Added reversible index hash for use in hash tables.

---

oss_src/unity/python/sframe/sys_util.py

Now, calling sframe.sys_util.test_pylambda_worker() runs both
simulated and unsimulated pylambda worker tests, packages all logs
into a zip file, and prints the name of that zip file.  Users having
pylambda issues can then submit this zip file to allow us to debug.

Added significantly improved pylambda test script

---

oss_src/unity/lib/unity_sframe.cpp
oss_src/unity/python/sframe/util/__init__.py

Fixes issue #254
The right error message was always there, we were just detecting
everything as a web protocol. That's fixed.
Also fixed the deprecated "local://" and "remote://" paths. For kicks
mostly.

Fix confusing IO error message

---

oss_src/unity/python/sframe/sys_util.py

- Sometimes we hit interesting long filename issues with zeromq with
the default $TMPDIR. change TMPDIR to /tmp before running the script.

Improved robustness of the test_pylambda_worker script on Mac.

---

oss_src/fault/CMakeLists.txt
oss_src/fault/sockets/async_reply_socket.cpp
oss_src/fault/sockets/async_request_socket.cpp
oss_src/fault/sockets/reply_socket.cpp
oss_src/fault/sockets/request_socket.cpp
oss_src/fault/zmq/print_zmq_error.cpp
oss_src/lambda/worker_pool.hpp

- A deep one inside of CPPIPC where sockets may get connected
incorrectly due to races in a global integer. Switch to an atomic.
- lambda worker ID needs to be atomically incremented correctly. This
should have no other side effects since the ID is only printed and ever
actually consumed anywhere.
- Added a catch for std::exception& on worker spawn.
- Changed a bunch of messages which goes to cerr to go to logger instead.
@hoytak @haijieg

Fixed some lambda worker races

---

oss_src/unity/lib/unity_sarray.cpp
oss_src/unity/lib/unity_sarray_binary_operations.cpp
oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/test/test_sarray.py

- sarray.contains() can now query inside a list, an array, and a dict (for keys)
- Added an sarray.is_in() which is the inverse of sarray.contains()
- We can now cast from list to array
- Some code cleanup in operators. There was some really strange handling of vector types.

Improved .contains(), list to array.array casting. Operator code cleanup

---

oss_src/fault/sockets/socket_config.cpp

sys/socket.h and sys/un.h are Linux/Mac only headers.

Fixes a windows compilation issue

---

oss_src/sframe_query_engine/operators/all_operators.hpp
oss_src/sframe_query_engine/operators/operator_properties.cpp
oss_src/sframe_query_engine/operators/operator_properties.hpp
oss_src/sframe_query_engine/operators/ternary_operator.hpp
oss_src/unity/lib/api/unity_sarray_interface.hpp
oss_src/unity/lib/unity_sarray.cpp
oss_src/unity/lib/unity_sarray.hpp
oss_src/unity/python/sframe/cython/cy_sarray.pxd
oss_src/unity/python/sframe/cython/cy_sarray.pyx
oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/test/test_sarray.py
oss_test/sframe_query_engine/operators/CMakeLists.txt
oss_test/sframe_query_engine/operators/ternary_operator.cxx

Implements a ternary operator. A little like np.where. Extremely useful for replacing values in an SArray.
```
Returns an SArray with the same values as g with values above 10
clipped to 10
>>> g = SArray([6,7,8,9,10,11,12,13])
>>> SArray.where(g > 10, 10, g)
dtype: int
Rows: 8
[6, 7, 8, 9, 10, 10, 10, 10]
Returns an SArray with the same values as g with values below 10
clipped to 10
>>> SArray.where(g > 10, g, 10)
dtype: int
Rows: 8
[10, 10, 10, 10, 10, 11, 12, 13]
Returns an SArray with the same values of g with all values == 1
replaced by None
>>> g = SArray([1,2,3,4,1,2,3,4])
>>> SArray.where(g == 1, None, g)
dtype: int
Rows: 8
[None, 2, 3, 4, None, 2, 3, 4]
```
Also fixes a bunch of oddities with SArray.from_const.
Previously,
```
gl.SArray.from_const([1], 10, list)
```
will produce …

Ternary operator

---

oss_src/unity/python/sframe/__init__.py
oss_src/unity/python/sframe/sys_util.py
oss_src/unity/python/sframe/test/test_environment_config.py

This PR allows the user to permanently write environment variables to
a common config file, then have those values be persistent across
sessions.
Use sys_util.get_config_file() to return the name of this config file.
Use sys_util.write_config_file_value(k, v) to write a value to this config file.

Loading environment variables from a config file

---

oss_src/fileio/fixed_size_cache_manager.cpp
oss_src/fileio/fixed_size_cache_manager.hpp
oss_test/fileio/fixed_size_cache_manager_test.cxx

See http://en.cppreference.com/w/cpp/memory/new/set_new_handler
If a memory allocation failure occurs, we get a chance to flush caches to
free up enough memory so that the allocation may succeed after that.

Added use of set_new_handler

---

oss_src/lambda/CMakeLists.txt
oss_src/lambda/worker_pool.cpp
oss_src/lambda/worker_pool.hpp

Makes the starting code to the lambda worker process more robust. 
env variable GRAPHLAB_LAMBDA_WORKER_CONNECTION_TIMEOUT now controls the timeout. Default is 60 seconds.  Setting to 0 means there is one try.  Setting to -1 means no timeout.

Robustification of lambda worker startup code.

---

oss_src/fault/CMakeLists.txt
oss_src/fault/sockets/socket_config.cpp
oss_src/fault/sockets/socket_config.hpp
oss_src/lambda/CMakeLists.txt
oss_src/lambda/worker_pool.cpp
oss_src/lambda/worker_pool.hpp
oss_test/lambda/dummy_worker.cpp
oss_test/lambda/worker_pool_test.cxx

Added GRAPHLAB_FORCE_IPC_TO_TCP_FALLBACK option
Added an option to force IPC to TCP fallback for all OS, not just
windows.

Lambda worker tcp forced fallback because a hypersquirrel says so

---

oss_src/image/png_io.cpp

The image_type uses boost::shared_ptr<char[]> to manage the image bytearray
in which the pointer is required to be allocated using C++ new char[].
In the png encoder, we use malloc/realloc. This fixes the leak by
makeing a copy of the png encoded memory buffer into a "new" allocated
array.

Fix memory leak in png_encode

---

oss_test/sframe_query_engine/optimizations.cxx

The global variable sliced_graph_memo causes problems because it holds on to
handles which are released after the global cache manager is released.

fixes a segfault at termination of optimizations.cxxtest

---

oss_src/fileio/fixed_size_cache_manager.cpp
oss_src/fileio/fixed_size_cache_manager.hpp
oss_test/fileio/fixed_size_cache_manager_test.cxx

Reverts dato-code/SFrame#311
This should not have worked. 
https://github.com/dato-code/SFrame/pull/311/files#diff-0d9c5131cf9be17dedddfe3a5cef5aacR258
```
ASSERT_FALSE(mutex.try_lock()) 
```
should always fail because this change changed the mutex to a recursive mutex.
We do indeed have tests that trigger the cache eviction behavior so I have no idea how this ever worked. I will investigate this in greater detail later, but for sanity in master, I am reverting this now.

Revert "Added use of set_new_handler"

---

oss_src/unity/python/setup.py

Ported from dato-code/dato-dev@8fb71dac879687b89b0a8f6ca4183b0d9bfd10a6
PyPI now seems to be rejecting classifiers for specific Windows versions
(at least in this format). GraphLab-Create uploaded successfully with
just "Windows" and no version.
Change-Id: I164b88287a3dead45a619d57966d78a2f8d9d82b

Fix windows classifier in setup.py

---

oss_src/unity/sdk/makefile_deploy

Without `.PHONY`, `make` might refuse to build these targets claiming they are up to date. However, these targets are by definition never up to date since they don't have dependencies specified in the Makefile. To be safe they should always rebuild.

Add PHONY targets to SDK makefile

---

oss_src/unity/extensions/random_sframe_generation.cpp

Generating the random sframe had 2 minor issues, which this fixes:
- Dicts always had a {0 : 0} key.  Now they are consistently {string : value}.
- hashes had a big block of zeros.  Now they actually look like random hashes.

Cleanup of issues in generating random sframes.

---

oss_local_scripts/make_egg.sh

Stop publishing metrics for `sframe` package. Remove `--prod` flag, it wasn't doing anything but metric publishing. This fixes #344 
Standardize python language version number in file name. This will let PyPI pick the right version of python 3 (i.e. 3.4 or 3.5). It will also prevent PyPI from installing `sframe` on a system with a Python version less than 2.7

Make Egg Updates

---

oss_src/unity/python/sframe/data_structures/sgraph.py

I originally thought this was a bug. I thought the name of the id column (in the vertices sframe) should be "vid_field", not that it should match the value of the vid_field parameter. Similar issue with the edge sframe. I think this small wording change makes things a lot clearer.

Clarifed Some Wording
