turi-code/SFrame

README.md

I updated the README.md file to populate it with documentation to help people get started.

[Readme] Updated README.md

---

oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/test/test_sframe.py

Addresses https://github.com/dato-code/SFrame/issues/25.

Fixed a cache invalidation bug.

---

oss_src/unity/lib/unity_sarray_binary_operations.cpp
oss_src/unity/python/sframe/cython/cy_sarray.pxd
oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/test/test_sarray.py

This PR fills out the above operations on an SArray, addressing https://github.com/dato-code/SFrame/issues/14.

Added __pow__, __abs__, __neg__, __pos__ ops for SArray.

---

.travis.yml

This PR switches the travis integration tests to debug mode from release mode.

Enable debug mode for tests on travis.

---

oss_src/unity/python/sframe/_gl_pickle.py
oss_src/unity/python/sframe/test/test_file_util.py
oss_src/unity/python/sframe/util/file_util.py

1. Added 'sync' S3 command to allow sync local folder and s3 folder.
2. Fixed a bug where we required too much permission when downloading file from S3
3. Fixed gl_pickler usage of file-util where the aws_credentials are not passed in
4. Moved file_util test code from close source to open source
@TobyRoseman

Small changes to file_util

---

oss_src/unity/python/sframe/_gl_pickle.py
oss_src/unity/python/sframe/test/test_gl_pickler.py

The get_aws_credentials() signature does not match what file_util
is expecting. Fix it to create a dictionary instead of passing in
as a pair
Also added tests for gl_pickler.

Fix gl_pickler code

---

oss_src/minipsutil/minipsutil.c
oss_src/startup_teardown/startup_teardown.cpp
oss_src/unity/server/unity_server.cpp

- Tweaked the memory limit tuning procedure a bit to be much more conservative to take into consideration that we may not be the only process on the system. (i.e. tune to half the system memory rather than all of the system memory)
- Added support for detection of memory limit inside of a cgroup.
addresses #34

Memory Limit tuning

---

oss_src/fileio/fs_utils.cpp
oss_test/fileio/general_fstream_test.cxx

This will be very helpful for sf._save_reference.

Improvements to relative path computation.

---

oss_src/sframe_query_engine/planning/optimizations/logical_filter_transforms.hpp

Fixes https://github.com/dato-code/SFrame/issues/20.  This one needs an annoying amount of infrastructure to test that it does what it's supposed to do, so this was just manually verified.

Fix for query opt issue in which transform nodes can be duplicated

---

oss_src/sframe_query_engine/planning/optimizations/general_union_project_transforms.hpp
oss_src/sframe_query_engine/planning/optimizations/optimization_transforms.cpp
oss_src/sframe_query_engine/planning/planner.cpp

Added an optimization to only materialize columns which need materializing.
i.e.
```
sf["new_column"] = ... something complicated ...
sf.__materialize__()
```
the materialize call should only materialize the new column and do not have to rewrite the entire sframe.

Partial Column Materialization

---

oss_src/unity/python/sframe/test/test_file_util.py
oss_src/unity/python/sframe/test/test_gl_pickler.py

Use relative path in the following test:
test_file_util.py
test_gl_pickle.py

Use relative path in file_util and gl_pickle tests

---

oss_src/sframe/sframe.cpp
oss_src/sframe/sframe.hpp
oss_src/unity/lib/gl_sarray.cpp
oss_src/unity/lib/gl_sarray.hpp
oss_src/unity/lib/gl_sframe.cpp
oss_src/unity/lib/gl_sframe.hpp
oss_src/unity/lib/unity_sframe.cpp
oss_src/unity/lib/unity_sframe.hpp
oss_test/unity/gl_sarray.cxx
oss_test/unity/gl_sframe.cxx

Added:
- Implicit casting operators from sframe/sarray to gl_sframe/gl_sarray.
- materialize_to_sframe and materialize_to_sarray.
- added contains_column and column_name(index).

Filling out the gl_sframe/gl_sarry API

---

oss_src/sframe/CMakeLists.txt
oss_src/unity/python/sframe/data_structures/sketch.py
oss_src/unity/python/sframe/toolkits/_main.py
oss_src/unity/python/sframe/util/__init__.py

- Add metric tracking to ToolkitError
- Remove quantile from the event_name for sketches
- Silence log messages on pylambda_worker launch

Minor tweaks from the other side

---

oss_src/unity/python/sframe/test/test_extensions.py

last PR had tabs which didn't show in github.

tabs --> spaces

---

oss_src/unity/python/sframe/data_structures/sframe.py

int is sometimes long on windows

Minor Fix to CSV Type inference

---

oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/test/test_sarray.py
oss_src/unity/python/sframe/test/test_sframe.py

It can be useful at times to have these shortcut functions
```
sframe.to_numpy()
and 
sarray.to_numpy()
```

Added SFrame.to_numpy and SArray.to_numpy functions

---

oss_src/logger/logger.cpp

Change-Id: I65cf2e32d3489334ff2e27545b1dd4aa178e5600

Fixed a log std thing so things compile on windows.

---

oss_src/lambda/pylambda_worker.cpp
oss_src/logger/CMakeLists.txt
oss_src/logger/logger.hpp

This should have been part of the earlier PR, but got accidentally dropped.

Moved process out of logging as a dependency.

---

oss_src/unity/python/sframe/toolkits/_internal_utils.py

The deleted utils are used by GraphLab Create, but not used
anywhere in the SFrame package.

Remove some unused toolkits utils.

---

oss_src/unity/python/sframe/cython/cy_flexible_type.pxd
oss_src/unity/python/sframe/cython/cy_flexible_type.pyx
oss_src/unity/python/sframe/cython/cy_model.pxd
oss_src/unity/python/sframe/cython/cy_variant.pxd
oss_src/unity/python/sframe/cython/cy_variant.pyx
oss_src/unity/python/sframe/extensions.py

This PR gives cy_variant.pyx the same love that cy_flexible_type.pyx
has received.

Rewrite of cy_variant.pyx for faster variant type conversion

---

oss_src/unity/python/sframe/cython/cy_variant.pyx
oss_src/unity/python/sframe/test/test_extensions.py

Nested variant type translations sometimes had random or dropped
elements if sufficiently nested.  This adds tests and fixes those
bugs.

BUGFIX: Bugfix for variant type translations

---

oss_src/sframe/group_aggregate_value.cpp
oss_src/sframe/groupby_aggregate_operators.hpp
oss_src/unity/python/sframe/aggregate.py
oss_src/unity/python/sframe/test/test_sframe.py

- FREQ_COUNT (Frequency counter for strings/ints)
sf.groupby("user",
{'rating_distinct':gl.aggregate.FREQ_COUNT('rating')})
- DISTINCT (distinct values in each group)
sf.groupby("user",
{'rating_distinct':gl.aggregate.DISTINCT('rating')})

Added 2 new groupby aggregates.

---

oss_src/unity/extensions/grouped_sframe.cpp
oss_src/unity/extensions/grouped_sframe.hpp

- GroupedSFrame now has additional methods to access underlying data.
- GroupedSFrame also has a `group_info` method that gives you access
to the groups and sizes of each group quickly.

[#Grouped SFrame] Added some enhancements to GroupedSFrame.

---

oss_src/sketches/countmin.hpp

Some methods in countmin sketch needs to be const
Also
- Added serializer/deserializer
- Seeding option

Minor Countmin sketch improvements

---

oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/test/test_sframe.py

Formalizes and documents the steps taken to determine the column types
of an SFrame given a result set from a DBAPI2 cursor. Prior to this,
column_type_hints didn't work as documented, and now results in a
Python-side cast to the hinted types. This also tries to make a best
effort not to fail on type conversion, and adds a check to see if a
returned type is actually supported by SFrame, falling back to string if
it's not.

Update type determination in from_sql

---

oss_src/flexible_type/flexible_type.cpp
oss_src/flexible_type/flexible_type.hpp
oss_src/unity/extensions/additional_sframe_utilities.cpp
oss_src/unity/extensions/additional_sframe_utilities.hpp
oss_src/unity/lib/api/unity_sarray_interface.hpp
oss_src/unity/lib/gl_sarray.cpp
oss_src/unity/lib/unity_sarray.cpp
oss_src/unity/lib/unity_sarray.hpp
oss_src/unity/python/sframe/cython/cy_sarray.pxd
oss_src/unity/python/sframe/cython/cy_sarray.pyx
oss_src/unity/python/sframe/data_structures/sarray.py

- Move subslice method into unity_sarray
- Add two apply callback methods to additional_sframe_utilities

Move sarray subslice out of extension

---

oss_src/unity/lib/unity_global.cpp

Reverts dato-code/SFrame#200
This causes more issues than it solves unfortunately.

Revert "fix sdk sharedlibrary open"

---

oss_src/shmipc/shmipc.cpp

This is to address some oddities in creating shmipc servers.  It then falls back to tcp.

Added error checking / fallback for SHM IPC.

---

oss_src/unity/python/sframe/__init__.py

Avoid excess engine starts for each lambda worker

---

oss_src/unity/python/sframe/test/test_json.py

- Fixed a relative import.
- Avoid printing the unicode string since on some terminal encoding
types that will fail.

More test_json fixes

---

oss_src/sframe/CMakeLists.txt
oss_src/unity/python/sframe/data_structures/sframe.py

add fixes to support wasb protocol of azure storage account in spark integration code.

Spark sframe support wasb azure

---

oss_src/lambda/pylambda_worker.cpp

This is needed to track down lambda worker issues more intelligently.

Detailed logging for pylambda_worker exceptions.

---

oss_src/unity/python/sframe/_gl_pickle.py
oss_src/unity/python/sframe/cython/cy_cpp_utils.pxd
oss_src/unity/python/sframe/cython/cy_cpp_utils.pyx
oss_src/unity/python/sframe/cython/cy_model.pxd
oss_src/unity/python/sframe/cython/cy_model.pyx
oss_src/unity/python/sframe/cython/cy_unity.pyx
oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/extensions.py
oss_src/unity/python/sframe/test/test_json.py
oss_src/unity/python/sframe/test/util.py
oss_src/unity/python/sframe/toolkits/_internal_utils.py
oss_src/unity/python/sframe/util/__init__.py
oss_src/unity/python/sframe/util/file_util.py
oss_src/unity/python/sframe/util/metric_tracker.py
oss_src/unity/python/sframe/util/type_checks.py

Sync from internal repo

---

oss_src/unity/python/sframe/data_structures/sframe.py

#242 
This is my first time contributing to an open source project.
Please review and give advice. Thanks!

Allow customizing number of lines used for column type inferring in read_csv

---

oss_src/unity/python/sframe/data_structures/sframe.py

JSON docs made reference to CSV

Documentation typo

---

oss_src/unity/lib/unity_sarray_binary_operations.cpp
oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/test/test_sarray.py
oss_src/unity/python/sframe/test/test_sframe.py

Closes #88
CLoses #259
Little performance acceleration for pow of 0.5 (Call math.sqrt)

Bug fixes, datetime difference support, pow optimization

---

oss_src/lambda/worker_pool.hpp
oss_src/parallel/mutex.hpp
oss_src/parallel/pthread_tools.hpp
oss_src/parallel/thread_pool.cpp
oss_src/sframe/sarray_v2_block_manager.cpp
oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/sys_util.py
oss_src/unity/python/sframe/toolkits/_internal_utils.py
oss_src/unity/sdk/graphlab/graphlab.dox
oss_test/lambda/dummy_worker.cpp

- Improved robustness for lambda workers.
- improved termination robustness
- improved thread pool robustness

Sync from internal repo.

---

oss_src/sframe/csv_line_tokenizer.cpp
oss_test/sframe/sframe_csv_test.cxx

Fixes na value handling

---

oss_src/unity/lib/api/unity_sarray_interface.hpp
oss_src/unity/lib/unity_sarray.cpp
oss_src/unity/lib/unity_sarray.hpp
oss_src/unity/python/sframe/cython/cy_sarray.pxd
oss_src/unity/python/sframe/cython/cy_sarray.pyx
oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/test/test_sarray.py

This is very useful for creating an SArray of Nones.

Allowed from_const to take a type.

---

oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/data_structures/sframe.py

Fixes issue where sample is not deterministic with seed == 0

---

oss_src/unity/lib/unity_sarray.cpp

Add early termination support for .any() and .all()

---

oss_src/unity/lib/api/unity_sarray_interface.hpp
oss_src/unity/lib/unity_sarray.cpp
oss_src/unity/lib/unity_sarray.hpp
oss_src/unity/python/sframe/cython/cy_sarray.pxd
oss_src/unity/python/sframe/cython/cy_sarray.pyx
oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/test/test_sarray.py

These are very useful for things like exact subsampling, sorting, etc.

Add SArray.hash() and SArray.random_integers()

---

oss_src/fileio/dmlcio/s3_filesys.cc

Merge the following dmlc improvements to s3 reader:
- [S3] more robust reader
https://github.com/dmlc/dmlc-core/commit/8e0c5a72d99436e158c262447a01ee7993bf3e81
- [S3] use recommend default timeout, and print an error msg when retry
https://github.com/dmlc/dmlc-core/commit/c4555165eff587a1fc240e4d252c30855542ffca

More robust s3 reader

---

oss_src/unity/lib/unity_sarray.cpp
oss_test/unity/gl_sframe.cxx

Fixes https://github.com/dato-code/SFrame/issues/289

Random split correct

---

oss_src/sframe/CMakeLists.txt

new spark_unity.jar version is uploaded to s3.

new_spark_unity_version

---

oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/test/test_sarray.py

This mirrors the SFrame.shape property and gives API compatibility with
Pandas series.

Add SArray.shape property

---

oss_src/parallel/parallel_includes.hpp
oss_src/util/generics/sparse_parallel_2d_array.hpp

Addresses https://github.com/dato-code/SFrame/issues/240.

Made parallel_all.hpp include the right stuff.

---

oss_src/unity/lib/unity_sarray_binary_operations.cpp
oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/test/test_sarray.py

Fixes https://github.com/dato-code/SFrame/issues/314

Reconciled div and floordiv for with python.

---

oss_src/parallel/atomic_ops.hpp
oss_test/parallel/CMakeLists.txt

- Better functionality (returns old values).
- Bugfix (type not respected)
- Documentation better.
- Now with C++ Tests.

Atomic ops improvement.

---

oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/test/test_sarray.py

This behaves the same as SFrame.random_split, but on a single column.

Add SArray.random_split

---

oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/python/sframe/data_structures/sgraph.py
oss_src/unity/python/sframe/test/test_sarray.py
oss_src/unity/python/sframe/test/test_sframe.py

Resolution of https://github.com/dato-code/SFrame/issues/85.

Added copy and deepcopy methods to SFrame, SArray, and SGraph.

---

oss_src/unity/extensions/json/decoder.cpp
oss_src/unity/extensions/json/encoder.cpp
oss_src/unity/lib/version_number.hpp
oss_src/unity/python/sframe/cython/cy_flexible_type.pxd
oss_src/unity/python/sframe/cython/cy_flexible_type.pyx
oss_src/unity/python/sframe/data_structures/image.py
oss_src/unity/python/sframe/data_structures/sarray.py
oss_src/unity/python/sframe/test/test_flexible_type.py
oss_src/unity/python/sframe/test/test_image_type.py
oss_src/unity/python/sframe/test/test_json.py
oss_src/unity/python/sframe/test/test_sarray.py
oss_src/unity/python/sframe/test/test_util.py
oss_src/unity/python/sframe/toolkits/_internal_utils.py
oss_src/unity/python/sframe/toolkits/_model.py
oss_src/unity/python/sframe/util/__init__.py
oss_src/unity/python/sframe/util/file_util.py
oss_test/parallel/atomic_ops.cxx

git subrepo pull --remote=git@github.com:hoytak/SFrame.git sframe
subrepo:
subdir:   "sframe"
merged:   "cc8c568"
upstream:
origin:   "git@github.com:hoytak/SFrame.git"
branch:   "master"
commit:   "6563c26"
git-subrepo:
version:  "0.3.0"
origin:   "???"
commit:   "???"
Change-Id: Ic929ec47c54d7ead08494aa9534277417c1cc1ba

Merge of updates in internal repository.

---

oss_src/cppipc/server/comm_server.cpp
oss_src/nanosockets/CMakeLists.txt
oss_src/nanosockets/async_reply_socket.cpp
oss_src/nanosockets/async_reply_socket.hpp
oss_src/nanosockets/async_request_socket.cpp
oss_src/nanosockets/get_next_port_number.cpp
oss_src/nanosockets/get_next_port_number.hpp
oss_src/nanosockets/publish_socket.cpp
oss_test/nanosockets/CMakeLists.txt
oss_test/nanosockets/reqreptest.cxx

- Allow use of automatic tcp address
- allow seperation of start_polling and stop_polling

nanomsg improvements

---

oss_src/lambda/worker_pool.hpp
oss_src/unity/python/README.txt
oss_src/unity/python/doc/source/_themes/sphinx_rtd_theme/layout.html
oss_src/unity/python/sframe/data_structures/sframe.py
oss_src/unity/sdk/doxygen/header.html

Change-Id: Iab6d0f6088d4070815606f41b2194291b7acfed2

Some URL changes/updates
